language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ThisTokenNeedsToBeGeneratedByJorge-WithEnablingCoverityScanAsServiceInGithub-ItIsFreeForOpenSourceProjectsAndMuchBetterThanLint"

addons:
  coverity_scan:
    project:
      name: "JorgeCastilloPrz/AndroidFillableLoaders"
      description: "FillableLoader library and sample app"
    notification_email: ""
    build_command_prepend: ""
    build_command:   "./gradlew checkstyle build"
    branch_pattern: master

script:
  ./gradlew checkstyle build
